"""create tables.

Revision ID: 79bd77bf0ab8
Revises: 
Create Date: 2018-06-03 19:17:35.851553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79bd77bf0ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classify_create_time', table_name='classify')
    op.drop_index('name', table_name='classify')
    op.drop_index('uuid', table_name='classify')
    op.drop_table('classify')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classify',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('create_time', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('uuid', 'classify', ['uuid'], unique=True)
    op.create_index('name', 'classify', ['name'], unique=True)
    op.create_index('ix_classify_create_time', 'classify', ['create_time'], unique=False)
    # ### end Alembic commands ###
